[project]
name = "machine-learning-crash-course"
version = "0.1.0"
description = "Google Machine Learning Crash Course"
readme = "README.md"
authors = [
    {name = "Farzad FARID", email = "farzy@farzy.org"},
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "jupyter",
    "numpy",
    "pandas",
    "tensorflow",
    "scikit-learn",
    "seaborn",
]

[tool.uv]
package = false
default-groups = []
